title: Public Data Library
description: Public Data Library is an organization committed to government transparency and promotes transparency by maintaining a free online public library of otherwise hard to get government files.

# GitHub information
# This is used for adding an edit this page link to the footer
github_info:
  organization: PublicDataLibrary
  repository: publicdatalibrary.org
  default_branch: main

# Configuration for setting the site width to 100%
# To enable, uncomment the following line
# site_width: wide

# Configuration for Google Analytics, add your UA code here:
# google_analytics_ua: UA-????????-??

# Configuration for DAP, add your agency ID here:
# dap_agency: GSA

# Uncomment to enable AnchorJS functionality on docs layout.
# See https://github.com/bryanbraun/anchorjs for more information.
anchor_js_targets: [h1, h2, h3, h4, h5, h6]

# To enable search, uncomment the search section
# You will need to setup a search account with search.gov
# https://search.usa.gov/signup
# Your search_site_handle value is from the search.gov settings page.

# search_site_handle: searchgov-site-handle

# Configuration for projects and team collections
# See https://jekyllrb.com/docs/collections/ for more information about collections.
# collections:
#   projects:
#     output: true
#   team:
#     output: true

remote_theme: 18F/uswds-jekyll

author:
  name: Public Data Library
  url: https://publicdatalibrary.org
  twitter: publicdatalib

# Compress Sass
sass:
  style: compressed

# Jekyll Site Map
url: "https://publicdatalibrary.org" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag